### ISSUE TITLE
Sound problem.

### ISSUE THREAD

**Issue by Achaean** [NagyD/SDLPoP#126]
**Hi!** :-)

I installed SDLPoP v1.17 at my system (Debian Jessie x64 KDE) and everything works great except from the sound.
Every sound played (eg. a closing door, or a falling floor), followed by a terrible noise (like scratching something).
SDL v.2.02.

**Comment by rrebello** [comment]
Hi, Achaean

Have a look at issue #64.

**Comment by NagyD** [comment]
Hi Achaean,

The old buggy SDL version seems to be the problem.
If your Linux distro does not have the newest SDL, you can always compile it from the sources: https://libsdl.org/download-2.0.php
Alternatively, you could manually undo the changes by commit ba1fd9d58f5e8ee62f14a8939669cb0094cf6c7a. (At least the `desired->format`.)

Hm, maybe I could add some code to detect this bug and automatically set sound format to 8-bit if the bug is present? (With a note on the console?)

**Comment by Achaean** [comment]
Hi! :-)

I built the latest stable SDL from source, but prince executable complains that it can't find libSDL2_image-2.0.so.0. 
I think I'll wait for the next Debian version (supposed to be just around the corner), which comes with SDL v.2.0.5.

**Comment by rrebello** [comment]
Achaean,

Besides SDL2, SDLPoP v1.17 also requires SDL2_image and SDL2_mixer, which are separate libraries whose sources you can download from https://www.libsdl.org/projects/SDL_image/ and https://www.libsdl.org/projects/SDL_mixer/ respectively.

Ideally, you should build these libraries from source and install them just like you did for SDL2, but If you really don't want to go through the hassle of doing that, you could simply try to install Debian packages 'libsdl2-image-dev' and 'libsdl2-mixer-dev'. The versions of the libraries that come with these packages work well with SDL2 v2.0.5 (I've tested it).

Beware though that the mentioned Debian packages end up pulling 'libsdl2-2.0-0' since they depend on it, so this procedure might not work depending on where you installed the SDL2 library you built from source. If you just used the default setting of installing it to '/usr/local/lib', you're fine as it won't get overwritten by the one that comes from the Debian package. Also, it will be the one picked by the prince executable since '/usr/local/lib' takes precedence over '/usr/lib' (in Debian at least).

**Comment by Achaean** [comment]
Ooops!!! I didn't notice that! :-(

Indeed installing SDL Image and Mixer did the trick! :-)
A bit of tweaking was needed (editing the ld.so.conf and running ldconfig), but the SDL FAQ page, was really useful.
Everything is fine now! :-)

Well it was the buggy SDL version problem after all.
**Sorry** for this (duplicate) post and **many thanks** for your help!!! :-)
