### ISSUE TITLE
Mods problem (Linux only).

### ISSUE THREAD

**Issue by Achaean** [NagyD/SDLPoP#129]
**Hi!** :-)

Seems like SDLPoP (v.1.17, compiled locally) has problems playing mods on Linux (I'm on Debian Jessie x64 KDE).

Sometimes it can't load the mod's graphics and - or music and uses the original ones and sometimes are loading them but can't load the mod levels and uses the originals (depending on the mod).

At Windows (I'm on 10 x64, SDLPoP  same version, binary downloaded from popot.org)) it plays mods flawlessly.

I'm using the method of extracting the mod at mod directory and editing the INI.

**Comment by NagyD** [comment]
My guess is that it's because not all mods have all DAT filenames in uppercase.
SDLPoP accesses all DAT files using all-uppercase filenames.
Filenames are case-sensitive on Linux.

So, when a mod has a DAT with lowercase name, SDLPoP can't find it in the mod's folder and it will use the original file instead.

Filenames are case-insensitive on Windows, so this is not a problem there.

Try renaming all files to all-uppercase in a problematic mod and tell me if it fixes your problem.

**Comment by Achaean** [comment]
**Indeed!**
Renaming the data files to uppercase solves the problem. :-)
I think, this note has to be added at mods.txt (maybe as a note to Linux users only).

**Thanks** Dávid **!!!** ;-)

**Comment by NagyD** [comment]
>  I think, this note has to be added at mods.txt (maybe as a note to Linux users only).

Done: 51ddeb82227009e47595f154039adb5ff4b027ef

> Thanks Dávid !!! ;-)

You're welcome! :-)
