### ISSUE TITLE
Error cross-compiling for ARMHF/V8 from Linux x86_64 (Debian 10)

### ISSUE THREAD

**Issue by LuizRafael79** [NagyD/SDLPoP#201]
Linking C executable /root/Downloads/SDLPoP/prince
CMakeFiles/prince.dir/seg009.c.o: In function `window_resized':
seg009.c:(.text+0x5d00): undefined reference to `SDL_RenderSetIntegerScale'
CMakeFiles/prince.dir/seg009.c.o: In function `set_gr_mode':
seg009.c:(.text+0x62a8): undefined reference to `SDL_RenderSetIntegerScale'
CMakeFiles/prince.dir/menu.c.o: In function `turn_setting_on_off':
menu.c:(.text+0x1308): undefined reference to `SDL_RenderSetIntegerScale'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/prince.dir/build.make:384: /root/Downloads/SDLPoP/prince] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/prince.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by NagyD** [comment]
[SDL_RenderSetIntegerScale](http://wiki.libsdl.org/SDL_RenderSetIntegerScale) was added in SDL 2.0.5.
Which version of SDL2 are you compiling with?

These errors occur should not occur with any SDL version, though, because we have added #if checks around all code which uses SDL_RenderSetIntegerScale to prevent these kinds of errors. [(example)](https://github.com/NagyD/SDLPoP/blob/master/src/menu.c#L1215)
Maybe your SDL2 headers and SDL2 libraries are different versions? Could you check that?

**Comment by LuizRafael79** [comment]
Sorry for It takes, but I don't know exactly what's going on, I'm using a toolchain to compile the code and then the final part came up, this problem occurred ... So I found out that I wasn't Pointing correctly to the libs and includes of the toolchain (target) but those of my system (host) but I didn't have time to deal with it again...

In time, i try to port this to PSC (Playstation Classic) but i dont know If possible to use Wayland+SDL2 only because PSC dont have Xorg support.

Thanks in advance

**Comment by NagyD** [comment]
So can I close this issue?

**Comment by LuizRafael79** [comment]
Yes i close It, thank you
